[package]
name = "feather-ecs"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
hecs = { git = "https://github.com/Ralith/hecs", rev = "4a19785" }
anyhow = "1"
log = "0.4"
resources = "1"
