[package]
name = "feather-ecs"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
hecs = { version = "0.1", package = "bevy_hecs" } # Watch https://github.com/Ralith/hecs/issues/71
