[package]
name = "feather-ecs"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
hecs = { git = "https://github.com/caelunshun/hecs", branch = "hashbrown-yanked" }
anyhow = "1"
thiserror = "1"
log = "0.4"
ahash = "0.6"
