[package]
name = "feather-server"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"
default-run = "feather-server"

[[bin]]
path = "src/main.rs"
name = "feather-server"

[lib]
path = "src/lib.rs"

[dependencies]
ahash = "0.7"
anyhow = "1"
base64 = "0.13"
base64ct = "1"
colored = "2"
common = { path = "../common", package = "feather-common" }
const_format = "0.2.22"
crossbeam-utils = "0.8"
data-generators = { path = "../../data_generators" }
either = "1.6.1"
fern = "0.6"
flate2 = "1"
flume = "0.10"
futures-lite = "1"
hematite-nbt = { git = "https://github.com/PistonDevelopers/hematite_nbt" }
indexmap = { version = "1", features = ["serde"] }
itertools = "0.10.3"
konst = "0.2.13"
libcraft = { path = "../../libcraft" }
log = "0.4"
md-5 = "0.10"
num-bigint = "0.4"
num-traits = "0.2"
once_cell = "1"
parking_lot = "0.12"
protocol = { path = "../protocol", package = "feather-protocol" }
quill = { path = "../../quill" }
rand = "0.8"
ring = "0.16"
rsa = "0.5"
rsa-der = "0.3"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
sha-1 = "0.10"
slab = "0.4"
time = { version = "0.3", features = ["local-offset", "formatting", "macros"] }
tokio = { version = "1", features = [ "full" ] }
toml = "0.5"
ureq = { version = "2", features = [ "json" ] }
utils = { path = "../utils", package = "feather-utils" }
uuid = "0.8"
vane = { path = "../../vane" }
worldgen = { path = "../worldgen", package = "feather-worldgen" }

[features]
# Use zlib-ng for faster compression. Requires CMake.
zlib-ng = ["flate2/zlib-ng-compat"]
