# Configuration for the Feather server.

[network]
address = "0.0.0.0"
port = 25565
# Packets with a size more than or equal to this value will be sent compressed.
# Compressing packets reduces bandwidth usage but increases CPU activity.
compression_threshold = 256

[server]
online_mode = true
motd = "A Feather server"
max_players = 16
default_gamemode = "creative"
view_distance = 12
# The default world where players will spawn on join
default_world = "default"

[log]
# If you prefer less verbose logs, switch this to "info".
# For development, it might be useful to set this to "trace".
level = "debug"

# UNINMPLEMENTED
[resource_pack]
# Server resource pack which is sent to players
# upon joining. Set this to an empty string to disable.
url = ""
# Optional SHA1 hash of the resource pack file.
hash = ""

# Worlds to configure at startup.
# Note that plugins may create additional worlds
# not in this config file.
[worlds.default]
# How the server will save chunks:
# - save_incrementally: save chunks at a time interval and on shutdown
# - drop_changes: never save chunks; changes are lost when chunks are unloaded (use only for immutable worlds)
# - keep_loaded: never save or unload chunks; changes are lost on server restart (useful for minigames with small maps)
save_strategy = { type = "drop_changes" }
dimension_type = "minecraft:overworld"
source = { type = "worldgen", generator = "flat" }
flat = true

[proxy]
# Select the IP forwarding mode that is used by proxies like BungeeCord or Velocity.
# Valid values are
# - "none" - for usage without a proxy or with feathers built in proxy
# - "bungee" - for BungeeCord/Waterfall/Travertine
# - "velocity" - for Velocity style proxies
proxy_mode = "none"

# For Velocity, you must specify the forwarding-secret from Velocity's
# velocity.toml file.
velocity_secret = ""
