[package]
name = "libcraft-chunk"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99"
bincode = "2.0.0-rc.1"
flate2 = "1"
libcraft-blocks = { path = "../blocks" }
libcraft-core = { path = "../core" }
itertools = "0.10"
once_cell = "1"
serde = { version = "1", features = [ "derive" ] }
