[package]
name = "feather-worldgen"
version = "0.1.0"
authors = ["caelunshun <caelum12321@gmail.com>"]
edition = "2018"

[dependencies]
feather-core = { path = "../core" }

rand = "0.7"
rand_xorshift = "0.2"

simdnoise = "3.1"

num-traits = "0.2"
