[package]
name = "feather-worldgen"
version = "0.6.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2021"

[dependencies]
libcraft = { path = "../../libcraft" }
log = "0.4"
quill = { path = "../../quill" }
rand = "0.8"
