[package]
name = "libcraft-blocks"
version = "0.1.0"
authors = ["Caelum van Ispelen <caelum12321@gmail.com>"]
edition = "2021"

[dependencies]
ahash = "0.7"
bincode = "2.0.0-rc.1"
bytemuck = { version = "1", features = ["derive"] }
flate2 = "1"
libcraft-core = { path = "../core" }
libcraft-items = { path = "../items" }
libcraft-macros = { path = "../macros" }
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
smartstring = { version = "1", features = ["serde"] }
thiserror = "1"
