[package]
name = "feather-base"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
blocks = { path = "../blocks", package = "feather-blocks" }
generated = { path = "../generated", package = "feather-generated" }
ecs = { path = "../ecs", package = "feather-ecs" }

resources = { version = "1", default-features = false }
vek = "0.12"
ahash = "0.4"
smallvec = "1"
bitflags = "1"
parking_lot = "0.11"
