[package]
name = "libcraft-generators"
version = "0.1.0"
authors = ["Kalle Kankaanpää"]
edition = "2018"

[dependencies]
anyhow = "1"
bincode = "1"
flate2 = "1"
libcraft-blocks = { path = "../blocks" }
serde = "1"
serde_json = "1"
