[package]
name = "libcraft-generators"
version = "0.1.0"
authors = ["Kalle Kankaanpää"]
edition = "2021"

[dependencies]
anyhow = "1"
bincode = "2.0.0-rc.1"
convert_case = "0.5"
flate2 = "1"
fs_extra = "1"
indexmap = { version = "1", features = [ "serde" ] }
libcraft = { path = ".." }
libcraft-blocks = { path = "../blocks" }
libcraft-chunk = { path = "../chunk" }
libcraft-core = { path = "../core" }
log = "0.4"
once_cell = "1"
proc-macro2 = "1"
quote = "1"
regex = "1"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
ureq = { version = "2", default-features = false, features = [ "tls" ] }
