[package]
name = "feather-common"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
base = { path = "../base", package = "feather-base" }
ecs = { path = "../ecs", package = "feather-ecs" }
utils = { path = "../utils", package = "feather-utils" }

smartstring = "0.2"
uuid = "0.8"
log = "0.4"
