[package]
name = "feather-world-format"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bitvec = "1"
byteorder = "1"
ciborium = "0.2"
libcraft = { path = "../../libcraft" }
log = "0.4"
serde = { version = "1", features = [ "derive" ] }
zstd = "0.11"

[dev-dependencies]
tempfile = "3"
