[package]
name = "feather-common"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
ahash = "0.7"
anyhow = "1"
base = { path = "../base", package = "feather-base" }
derive_more = "0.99"
flume = "0.10"
itertools = "0.10"
libcraft-blocks = { path = "../../libcraft/blocks" }
libcraft-core = { path = "../../libcraft/core" }
libcraft-inventory = { path = "../../libcraft/inventory" }
libcraft-items = { path = "../../libcraft/items" }
log = "0.4"
parking_lot = "0.12"
quill = { path = "../../quill" }
rand = "0.8"
rayon = "1.5"
smartstring = "1"
tokio = "1"
utils = { path = "../utils", package = "feather-utils" }
uuid = { version = "0.8", features = [ "v4" ] }
vane = { path = "../../vane" }
worldgen = { path = "../worldgen", package = "feather-worldgen" }
