[package]
name = "feather-protocol"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
base = { path = "../base", package = "feather-base" }

anyhow = "1"
thiserror = "1"

flate2 = "1"
cfb8 = "0.5"
aes = "0.5"
bytes = "0.5"

serde = "1"
byteorder = "1"
uuid = "0.8"
hematite-nbt = { git = "https://github.com/PistonDevelopers/hematite_nbt" }
bytemuck = "1"
num-traits = "0.2"

parking_lot = "0.11" # Arc<RwLock<Chunk>> compat
