[package]
name = "feather-datapacks"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ahash = "0.4"
smartstring = { version = "0.2", features = ["serde"] }

ureq = { version = "1", default-features = false, features = ["tls"] }
anyhow = "1"
thiserror = "1"
log = "0.4"
zip = "0.5"
