[package]
name = "feather-server"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"
default-run = "feather-server"

[dependencies]
common = { path = "../common", package = "feather-common" }
base = { path = "../base", package = "feather-base" }
ecs = { path = "../ecs", package = "feather-ecs" }
protocol = { path = "../protocol", package = "feather-protocol" }
utils = { path = "../utils", package = "feather-utils" }

async-executor = "1"
async-io = "1"
futures-lite = "1"
either = "1"
flume = "0.8"

smartstring = "0.2"
ahash = "0.4"
uuid = { version = "0.8", features = ["v4"] }
anyhow = "1"
simple_logger = "1"
log = "0.4"
once_cell = "1"
rand = "0.7"

serde = { version = "1", features = ["derive"] }
toml = "0.5"
serde_json = "1"
hematite-nbt = "0.5"
base64 = "0.12"

# Authentication
rsa = { version = "0.3", default-features = false }
rsa-der = "0.2"
ureq = { version = "1", default-features = false, features = ["tls"] }
num-bigint = "0.3"
sha1 = "0.6"
sha2 = "0.9"
