# Configuration for the Feather server.

# Some options are unimplemented and have been labeled so.

[io]
# Packets with a size more than or equal to this value will be sent compressed.
# Compressing packets reduces bandwidth usage but increases CPU activity.
compression_threshold = 256

[server]
online_mode = true
motd = "@aqua A Feather server"
max_players = 16
default_gamemode = "creative"
difficulty = "none" # Unimplemented
view_distance = 6
address = "0.0.0.0"
port = 25565

[gameplay]
monster_spawning = true # Unimplemented
animal_spawning = true # Unimplemented
pvp = true # Unimplemented
nerf_spawner_mobs = false # Unimplemented
# Either "classic" for 1.8 PvP or "new" for 1.9
pvp_style = "classic" # Unimplemented

[log]
# If you prefer less verbose logs, switch this to "info."
# For development, it might be useful to set this to "trace."
level = "debug"

[resource_pack]
# Server resource pack which is sent to players
# upon joining. Set this to an empty string to disable.
url = ""
# Optional SHA1 hash of the resource pack file.
hash = ""

[world]
# The name of the directory containing the world.
name = "world"
# The generator to use if the world does not exist.
# Implemented values are: default, flat
generator = "default"
# The seed to use if the world does not exist.
# Leaving this value empty will generate a random seed.
# If this value is not a valid integer (i64), the string
# will be converted using a hash function.
seed = ""

[proxy]
# Select the IP forwarding mode that is used by proxies like BungeeCord or Velocity.
# Valid values are
# - "none" - for usage without a proxy
# - "bungee" - for BungeeCord/Waterfall/Travertine
# - "velocity" - for Velocity style proxies (unimplemented)
proxy_mode = "none"
